id: "task2-http-get"
description: "Задача для выполнения HTTP GET запроса."
triggers:
  - type: "schedule"
    schedule: "0 * * * * *" # Каждую минуту
action:
  type: "http"
  http_request:
    url: "https://httpbin.org/get?param=value"
    method: "GET"
    headers:
      X-Custom-Header: "GoTaskManager"
notify:
  type: "file"
  file_notification:
    file_path: "/tmp/task_alerts.log"
    message: "Task my-main-task completed successfully at {{.Date}} {{.TaskID}} {{.Data}}."
    append: true
