id: "example-child"
description: "Дочерняя задача, запускается только при успешном завершении example-parent."
depends_on:
  - task_id: "example-parent"
    status: "success"
action:
  type: "command"
  command:
    path: "echo"
    args: ["Родитель: {{.ParentTaskID}}", "Дата: {{.ParentDate}}", "Данные: {{.ParentData}}"]
notify:
  - type: "file"
    file_notification:
      file_path: "/tmp/example_child_notify.log"
      message: "Дочерняя задача {{.TaskID}} выполнена после успеха родительской. Время: {{.Date}}"
      append: true
